### ISSUE TITLE
RoadMap/功能规划

### ISSUE THREAD

**Issue by yedf2** [yedf/dtm#116]
Roadmap：
* [x] 事务模式支持
	* [x] SAGA 支持（含并发）
	* [x] TCC 支持（含嵌套）
	* [x] XA 支持
	* [x] 消息 支持（含事务消息）
* [x] 数据库支持
	* [x] Mysql支持（含Mariadb、TiDB）
	* [x] Postgres支持
* [ ] Redis 支持
	* [x] Redis存储引擎支持
	* [ ] 空URL支持（高性能测试需要）
	* [ ] 日志分级（高性能测试需要）
	* [ ] 测试报告
* [ ] Header 支持
	* [ ] HTTP Header支持
	* [ ] gRPC Header支持
* [ ] dtm 独立部署（类似etcd，支持一键启动，不依赖数据库）
	* [x] 支持内嵌boltdb存储引擎
	* [ ] examples独立成单独项目
	* [ ] quick start改为不需要数据库
	* [ ] 支持homebrew安装dtm
	* [ ] 支持apt install安装dtm
	* [ ] 给dtm申请iana端口号
* [ ] 消息型事务添加功能
	* [ ] 事务消息的回查自动处理（WIP，专利申请中）
	* [ ] Web管理后台
* [ ] XA 优化
	* [ ] 给mariadb提PR，增加xa recover中事务的持续时间
	* [ ] （可能）给mariadb提PR，允许指定条件查询进行中的xa事务
	* [ ] （可能）给mariadb提PR，允许连接B提交连接A中prepare的事务，无需A断连
	* [ ] 优化dtm的XA实现
* [ ] HTTP接口实现优化
	* [ ] （可能）将HTTP的接口gin实现，改为grpc-gateway实现

**Comment by lsytj0413** [comment]
- 使用 cobra 来管理各种启动的子命令
- 使用 viper 来管理配置

是不是可以加上？

**Comment by yedf2** [comment]
目前子命令不多，主要是在examples里面，可以看看后面的复杂度

viper之前试过，貌似帮助并没有很大，目前的代码，加载yaml和env，看起来暂时够用

**Comment by tianmingxing** [comment]
@yedf2 怎么将TC事务协调器和TM子事务管理器合并到一起了？

**Comment by csimplestring** [comment]
大佬，除了支持接入http，grpc，是否考虑支持直接传入action，compensation函数？

因为在开发过程中，经常会
- 直接使用其他服务提供的sdk
- 有些第三方的服务不支持http，grpc，比如直接使用jdbc，写一个http的wrapper又比较繁琐

如果能直接传入函数的话，就非常方便了，比如go中
``` Go
func action1(payload interface) error {
}

func compensate1(payload interface) error {
}

func action2(payload interface) error {
}

func compensate2(payload interface) error {
}

saga := dtm.NewSaga(...)
             .Add(action1, compensate1, payload)
              .Add(action2, compensate2, payload)

saga.Commit()
```

不知这个提议是否有欠考虑的地方？

**Comment by csimplestring** [comment]
提供 helm chart或者直接上k8s的operator，就更方便k8s上的部署

**Comment by yedf2** [comment]
> 提供 helm chart或者直接上k8s的operator，就更方便k8s上的部署

欢迎社区能够帮忙贡献

**Comment by yedf2** [comment]
> 大佬，除了支持接入http，grpc，是否考虑支持直接传入action，compensation函数？

对于你给出的这个场景，因为所有函数在本地，所以本地事务就能够解决绝大部分，剩下跨数据库的很少，没必要单独支持

> 还有就是0.18之后example folder消失了，跪求那么多的例子能回来啊

在最新版本的README里面，有一个单独的dtm-examples项目链接，原先的例子，全部都拆分到这个项目了

**Comment by Coneboy-k** [comment]
能否添加 prometheus  监控？

**Comment by wooln** [comment]
What's the unfinished  "Cluster version",  the same as [Foundation #dtm-multi-instances-solution | DTM tutorial](https://en.dtm.pub/deploy/base.html#dtm-multi-instances-solution) ?

**Comment by wooln** [comment]
Expect admin page authentication,

**Comment by relxet** [comment]
> Expect admin page authentication.

no need, use nginx auth basic
